version: '2.1'

services:

  builder-integration:
    image: "remkolomna/webplanner:builder-e2e-${COMPOSE_PROJECT_NAME}"
    build:
      context: ../../Builder
      dockerfile: Dockerfile
    command: /opt/builder/Builder --integration
    environment:
      FM_BUILDER_DATADIR: /var/opt/fm
    networks:
      - app-network-integration

  webplanner-integration:
    image: "remkolomna/webplanner:webplanner-e2e-${COMPOSE_PROJECT_NAME}"
    build:
      context: ..
      dockerfile: Dockerfile
    command: yarn run testci
    environment:
      IS_CI: "true"
    depends_on:
     - "builder-integration"
    networks:
      - app-network-integration

networks:
  app-network-integration:
    driver: bridge
